name: Linters & Tests

on:
  push:
    # branches: [ $default-branch ]
  pull_request:
    branches:
      - $default-branch

jobs:
  linters_n_tests:
    uses:
      wavefrontHQ/wavefront-sdk-python/.github/workflows/main.yml@austinov/rebranding
