name: Linters & Tests

on:
  push:
    # branches: [ $default-branch ]
  pull_request:
    branches:
      - $default-branch

jobs:
  call_linters_n_tests:
    uses: wavefrontHQ/wavefront-sdk-python/.github/workflows/main.yml@master
    with:
      env_yml: ./.github/workflows/env.yml
