name: Upload Python Package Onto TestPyPI

on:
  push:
    branches:
      - $default-branch

jobs:
  setenv:
    uses: ./.github/workflows/env.yml
  publish_on_merge:
    needs: setenv
    uses:
      wavefrontHQ/wavefront-sdk-python/.github/workflows/on_merge.yml@master
    with:
      package_name: ${{ needs.setenv.output.package_name }}
      requirements: ${{ needs.setenv.output.requirements }}
